on: pull_request

name: Continuous Integration

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
    - name: Coverage
      run: bazel coverage --combined_report=lcov //...
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: $(bazel info output_path)/_coverage/_coverage_report.dat
        minimum-coverage: 20
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working_directory: $(bazel info output_path)/_coverage/
        update-comment: true
