on: pull_request

name: PR annotations
permissions:
  pull-requests: write

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
    - name: Retrieve path
      run: |
        echo "COV_PATH=$(bazel info output_path)" >> $GITHUB_OUTPUT
      id: covpath
    - name: Coverage
      run: bazel coverage --instrument_test_targets --experimental_cc_coverage --combined_report=lcov //...
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: ${{ steps.covpath.outputs.COV_PATH }}/_coverage/_coverage_report.dat
        minimum-coverage: 20
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./
        update-comment: true
