on:
  pull_request:
    branches: [ master ]
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # for Sigstore OIDC
    outputs:
      image: ${{ steps.build.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/epsxy/flower

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set image outputs
        run: |
          echo "image=ghcr.io/epsxy/flower:${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/epsxy/flower:${GITHUB_REF_NAME})
          echo "digest=$digest" >> $GITHUB_OUTPUT

  provenance:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      packages: write
    if: startsWith(github.ref, 'refs/tags/')
    workflow_call:
      workflow: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
      with:
        image: ${{ needs.build.outputs.image }}
        digest: ${{ needs.build.outputs.digest }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
